'use client'
import { ContentfulLivePreviewProvider } from "@contentful/live-preview/react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import HeaderController from "@/components/header/HeaderController"
import "./globals.scss"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ContentfulLivePreviewProvider
          locale="en-US"
          enableInspectorMode={true}
          enableLiveUpdates={true}
        >
          {/* <HeaderController /> */}
          {children}
        </ContentfulLivePreviewProvider>
        {/* {children} */}
      </body>
    </html>
  );
}
